/**
 * @file  main.c
 * @brief  Entry point for the demo assembler/parser.
 *
 * This tiny driver program demonstrates the full compilation pipeline
 * built from the components you’ve defined:
 *   1️⃣ **Lexing** – performed by `lexer.h` (generated by Flex/Bison).
 *   2️⃣ **Parsing** – `parser.h` consumes the source string and produces a
 *      `statement_list_t` (a list of `statement_t` objects).
 *   3️⃣ **AST conversion** – `ast.h` turns the statement list into a
 *      `node_collection_t`, which holds arrays of `opcode_node_t` and
 *      `label_node_t`.
 *
 * The program parses a hard‑coded test string, reports the number of
 * statements found, converts them to the internal AST representation, and
 * then iterates over the generated labels and opcodes, printing each via the
 * logger.
 *
 * **Typical usage**
 *
 * ```sh
 * $ ./assembler_demo          # runs the built‑in test case
 * ```
 *
 * To adapt this driver for real input you could replace the `test[]` literal
 * with a file read (`fopen`, `fread`) or command‑line argument handling.
 *
 * **Dependencies**
 *
 *   - `<clogger.h>` – lightweight logging facility (must be linked in).
 *   - `<errno.h>`, `<stdio.h>`, `<stdlib.h>` – standard C library.
 *   - `"ast.h"` – AST data structures and conversion functions.
 *   - `"bison.h"` – Bison‑generated parser declarations (if used directly).
 *   - `"lexer.h"` – Flex‑generated lexer interface.
 *   - `"parser.h"` – high‑level parsing API.
 *
 * **Memory ownership**
 *
 *   - `parser_parse_string` allocates a `statement_list_t`; the caller is
 *     responsible for freeing it (via a `parser_free_statement_list` helper,
 *     if you provide one).
 *   - `ast_convert_iteration_1` allocates a `node_colection_t` and the
 *     contained `opcode_node_t` / `label_node_t` objects.  The caller must
 *     release these resources when they are no longer needed.
 *
 * @author  R. Middel
 * @date   2025‑11‑19
 * @license MIT
 */

#include <clogger.h>
#include <errno.h>
#include <getopt.h>
#include <stdio.h>
#include <stdlib.h>

#include "ast.h"
#include "binary.h"
#include "bison.h"
#include "lexer.h"
#include "parser.h"

/* Define the long options */
static struct option long_opts[] = {
    {"help", no_argument, 0, 'h'},
    {"verbose", no_argument, 0, 'v'},
    {"output", required_argument, 0, 'o'},
    {"input", required_argument, 0, 'i'},
    {0, 0, 0, 0} /* terminator */
};
/* Short options string: h and v are flags, o and i requires an argument */
const char *short_opts = "hvio:";

/**
 * @brief Reads the entire content of a source file into a dynamically allocated
 * string.
 *
 * @param filename The path to the source file to read.
 * @return A pointer to the dynamically allocated string containing the file
 * content, or NULL if an error occurred.
 */
char *read_source_file(const char *filename)
{
  FILE *file = fopen(filename, "r");
  if (NULL == file) {
    clog_error(__FILE_NAME__, "Failed to open file %s: %s", filename,
               strerror(errno));
    return NULL;
  }

  fseek(file, 0, SEEK_END);
  long length = ftell(file);
  fseek(file, 0, SEEK_SET);

  char *buffer = malloc(length + 1);
  if (buffer == NULL) {
    clog_error(__FILE_NAME__, "Failed to allocate memory for file %s",
               filename);
    fclose(file);
    return NULL;
  }

  fread(buffer, 1, length, file);
  buffer[length] = '\0'; // Null-terminate the string

  fclose(file);
  return buffer;
}

/**
 * @brief Demo driver that parses a hard‑coded assembly snippet and prints the
 *        resulting AST information.
 *
 * This function performs the following steps:
 *
 * 1. Defines a small test program (`test[]`) containing a label, a couple of
 *    pseudo‑instructions, and a terminating label.
 * 2. Calls `parser_parse_string()` to convert the source text into a
 *    `statement_list_t`.  Memory for the list is allocated beforehand.
 * 3. Checks the parsing result:
 *    - If the pointer is `NULL` or the list contains zero statements, an error
 *      is logged via `clog_error`/`clog_info` and the program exits with
 *      `EXIT_FAILURE`.
 *    - Otherwise, the number of parsed statements is reported.
 * 4. Allocates a `node_collection_t` and invokes
 *    `ast_convert_itteration_1()` to translate the statement list into the
 *    internal AST representation (arrays of `opcode_node_t` and
 * `label_node_t`).
 * 5. Iterates over the generated label and opcode arrays, logging each entry
 *    with `clog_info`.  The loops advance the internal pointers (`labels++`,
 *    `opcodes++`) while checking for `NULL` termination.
 * 6. Returns `EXIT_SUCCESS` on successful completion.
 *
 * @param argc  Number of command‑line arguments (unused in the current demo).
 * @param argv  Argument vector (unused in the current demo).
 *
 * @return `EXIT_SUCCESS` if the demo runs without errors, otherwise
 *         `EXIT_FAILURE`.
 *
 * @note The function currently leaks the memory allocated for
 *       `statement_list_t`, `node_collection_t`, and the individual AST nodes.
 *       In production code you should free these structures with the
 *       appropriate cleanup functions (e.g. `parser_free_statement_list`,
 *       `ast_free_node_collection`, etc.).
 */
int main(int argc, char *argv[])
{

  int c;
  int verbose = 0;
  char *file_output = NULL;
  char *file_input = NULL;

  while ((c = getopt_long(argc, argv, short_opts, long_opts, NULL)) != -1) {
    switch (c) {
    case 'h': /* --help or -h */
      printf("Usage: %s [options] [files...]\n"
             "  -h, --help          Show this help\n"
             "  -v, --verbose       Enable verbose output\n"
             "  -o, --output FILE   Write results to FILE\n"
             "  -i, --input FILE    FILE with the sourcecode\n",
             argv[0]);
      exit(EXIT_SUCCESS);
    case 'v': /* --verbose or -v */
      verbose = 1;
      break;
    case 'o': /* --output=FILE or -o FILE */
      file_output = optarg;
      break;
    case 'i': /* --input=FILE or -i FILE */
      file_input = optarg;
      break;
    case '?': /* unknown option */
      /* getopt_long already printed an error message */
      exit(EXIT_FAILURE);
    default:
      abort(); /* should never happen */
    }
  }

  if (NULL == file_input || NULL == file_output) {
    clog_error(__FILE_NAME__, "Input or output file not specified");
    return EXIT_FAILURE;
  }

  // Load source code from file
  const char *source_code = read_source_file(file_input);

  if (NULL == source_code) {
    return EXIT_FAILURE;
  }

  statement_list_t *statements = malloc(sizeof(statement_list_t));
  // 1. Parse the program
  parser_parse_string(source_code, &statements);

  if (NULL == statements) {
    free((void *)source_code);
    clog_error(__FILE_NAME__, "Returned no statements");
    return EXIT_FAILURE;
  }

  if (0 == statements->count) {
    clog_info(__FILE_NAME__, "No statements parsed");
    free((void *)source_code);
    parser_free_statements(statements);
    return EXIT_FAILURE;
  } else {
    free((void *)source_code);
    clog_info(__FILE_NAME__, "Found %d statements", statements->count);
  }

  node_collection_t *node_collection = malloc(sizeof(node_collection_t));

  // 2. Perform the first itteration of the convertion
  ast_convert_iteration_1(statements, node_collection);

  // 3. Perform the second itteration of the convertion
  ast_convert_iteration_2(node_collection);

  // Store the program
  binary_write_program(file_output, node_collection);

  parser_free_statements(statements);
  ast_free_node_collection(node_collection);

  return EXIT_SUCCESS;
}
