/**
 * @file  parser.c
 * @brief  Implementation of the source‑code parser.
 *
 * This translation unit provides the concrete logic for turning a raw
 * assembly‑like string into an in‑memory abstract syntax tree composed of
 * `statement_t` objects (see parser.h).  The workflow is roughly:
 *
 *   1. Tokenise the input string.
 *   2. Recognise statements (labels or instructions) and their parameters.
 *   3. Allocate the corresponding data structures using the factory
 *      helpers declared in parser.h.
 *   4. Populate a `statement_list_t` that the rest of the program can walk.
 *
 * The file also supplies a small set of cleanup helpers that free the
 * dynamically allocated structures created during parsing.
 *
 * Public symbols (exported via the header):
 *
 *   - parser_create_parameter_string()
 *   - parser_create_parameter_integer()
 *   - parser_create_instruction()
 *   - parser_create_label()
 *   - parser_parse_string()
 *
 * All public functions are declared in <parser.h> and marked with
 * `extern "C"` when compiled under C++ (the header takes care of the
 * linkage guard).
 *
 * @author  R. Middel
 * @date    2025‑11‑19
 * @license MIT (or your project's license)
 */

#include "ast.h"
#include "bison.h"
#include "lexer.h"

/**
 * @brief Forward decleration of the yyparse function
 */
int yyparse(void *, statement_list_t **statements, yyscan_t scanner);

/**
 * @brief Parse a string into a statement list
 *
 * Parses the given input string and produces a statement list.
 * For the parsing, it uses the lexer and parser generated by Flex/Bison.
 *
 * @param expr  The input string to parse
 * @param statements  Output parameter to hold the resulting statement list
 * @return int  EXIT_SUCCESS on success, EXIT_FAILURE on error
 */
int parser_parse_string(const char *expr, statement_list_t **statements)
{
  yyscan_t scanner;
  YY_BUFFER_STATE state;
  YYLTYPE yylval;

  if (yylex_init(&scanner)) {
    /* could not initialize */
    clog_error(__FILE_NAME__, "Could not initialize yylex");
    return EXIT_FAILURE;
  }

  state = yy_scan_string(expr, scanner);

  if (yyparse(&yylval, statements, scanner)) {
    /* error parsing */
    clog_error(__FILE_NAME__, "yyparse failed");
    return EXIT_FAILURE;
  } else {
    clog_info(__FILE_NAME__, "Returned %d statements", (*statements)->count);
  }

  yy_delete_buffer(state, scanner);
  yylex_destroy(scanner);

  return EXIT_SUCCESS;
}

/**
 * @brief Create a string parameter
 *
 * Allocates and initializes a parameter_t representing a string parameter.
 *
 * @param name  The name of the parameter
 * @param value  The string value of the parameter
 * @return parameter_t*  Pointer to the newly created parameter
 */
parameter_t *parser_create_parameter_string(const char *name, const char *value)
{
  parameter_t *param = (parameter_t *)malloc(sizeof(parameter_t));
  if (!param) {
    perror("malloc");
    exit(EXIT_FAILURE);
  }
  param->name = strdup(name);
  param->type = STRING;
  param->value.string = strdup(value);
  return param;
}

/**
 * @brief Create an integer parameter
 *
 * Allocates and initializes a parameter_t representing an integer parameter.
 *
 * @param name  The name of the parameter
 * @param value  The integer value of the parameter
 * @return parameter_t*  Pointer to the newly created parameter
 */
parameter_t *parser_create_parameter_integer(const char *name, int value)
{
  parameter_t *param = (parameter_t *)malloc(sizeof(parameter_t));
  if (!param) {
    perror("malloc");
    exit(EXIT_FAILURE);
  }
  param->name = strdup(name);
  param->type = INTEGER;
  param->value.integer = value; // atoi(value);
  return param;
}

/**
 * @brief Create an instruction statement
 *
 * Allocates and initializes a statement_t representing an instruction.
 *
 * @param name  The name of the parameter
 * @param params  A list of parameters for the instruction
 * @param param_count  The number of parameters
 * @return statement*  Pointer to the newly created statement
 */
statement_t *parser_create_instruction(const char *name, parameter_t **params,
                                       size_t param_count)
{
  statement_t *statement = (statement_t *)malloc(sizeof(statement_t));

  statement->kind = TYPE_INSTRUCTION;
  statement->args.params = params;
  statement->args.count = param_count;
  statement->name = strdup(name);
  return statement;
}
/**
 * @brief Create a label statement
 *
 * Allocates and initializes a statement_t representing a label.
 *
 * @param name  The name of the label
 * @return statement*  Pointer to the newly created statement
 */
statement_t *parser_create_label(const char *name)
{
  statement_t *statement = (statement_t *)malloc(sizeof(statement_t));

  statement->kind = TYPE_LABEL;
  statement->args.params = NULL;
  statement->args.count = 0;
  statement->name = strdup(name);
  return statement;
}
